name: Changed Packages Action
description: Return the list of changed stdlib packages in a push or pull request.
author: Philipp Burckhardt <pburckhardt@outlook.com>

inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication
    required: true

runs:
  using: node20
  main: dist/index.js

outputs:
  packages:
    description: "Array of changed packages in a push or pull request"

branding:
  icon: box
  color: green