# Workflow name:
name: Test GitHub Action

# Workflow triggers:
on:
  push:

# Workflow jobs:
jobs:
  test:
    # Define the type of virtual host machine on which to run the job:
    runs-on: ubuntu-latest

    # Define the sequence of job steps...
    steps:
      - uses: actions/checkout@v3
      - id: changed-packages
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log output of the previous step
        run: |
          echo "This is the output of the previous step:"   
          echo ${{ join( fromJSON( steps.changed-packages.outputs.packages ), ' ' ) }}